"""Automated portfolio tracker — Streamlit UI.

Run with:  streamlit run app.py

The app reads a snapshot written by the automated pipeline if one exists
(data/snapshot.json), otherwise it computes everything live on load. This is
the same separation a production system uses: a scheduled job does the heavy
fetching, the UI just renders.
"""

from __future__ import annotations

import json
from pathlib import Path

import plotly.graph_objects as go
import streamlit as st

import config
from portfolio import build_summary
from digest import generate, benchmark_day_pct
from data import get_candles
from indicators import sma, ema, latest_rsi

SNAPSHOT = Path("data/snapshot.json")

st.set_page_config(
    page_title="Automated portfolio tracker",
    page_icon="📈",
    layout="wide",
)

# --------------------------------------------------------------------------- #
# Helpers
# --------------------------------------------------------------------------- #

GREEN = "#1D9E75"
RED = "#E24B4A"
GRAY = "#888780"


def colored(value: float, text: str) -> str:
    """Return markdown text colored green/red by sign."""
    color = GREEN if value >= 0 else RED
    return f"<span style='color:{color}'>{text}</span>"


def load_snapshot() -> dict | None:
    if SNAPSHOT.exists():
        try:
            return json.loads(SNAPSHOT.read_text())
        except Exception:
            return None
    return None


# --------------------------------------------------------------------------- #
# Header
# --------------------------------------------------------------------------- #

snapshot = load_snapshot()
mode = "Live (Finnhub)" if config.is_live() else "Demo data"

left, right = st.columns([3, 1])
with left:
    st.title("Automated portfolio tracker")
    st.caption(
        f"Data source: {mode} · pipeline writes a fresh snapshot every morning"
    )
with right:
    if snapshot:
        st.success(
            f"Pipeline OK · last run {snapshot.get('generated_at', 'unknown')}",
            icon="✅",
        )
    else:
        st.info("Computing live (no snapshot yet)", icon="⚡")

summary = build_summary()
bench = benchmark_day_pct()

tab_overview, tab_charts, tab_pipeline = st.tabs(
    ["Overview", "Charts", "Pipeline & runs"]
)

# --------------------------------------------------------------------------- #
# Overview tab
# --------------------------------------------------------------------------- #

with tab_overview:
    # Digest banner (use the pipeline's digest if present, else generate now)
    if snapshot and snapshot.get("digest"):
        digest_text = snapshot["digest"]["text"]
        digest_tags = snapshot["digest"]["tags"]
        digest_when = snapshot["digest"]["generated_at"]
        badge = "Auto-generated by pipeline"
    else:
        d = generate(summary, bench)
        digest_text, digest_tags, digest_when = d.text, d.tags, d.generated_at
        badge = "Generated on load"

    with st.container(border=True):
        st.markdown(f"**Today's digest** · _{badge} · {digest_when}_")
        st.markdown(digest_text)
        st.markdown(" ".join(f"`{t}`" for t in digest_tags))

    # Metric cards
    c1, c2, c3, c4 = st.columns(4)
    c1.metric("Portfolio value", f"${summary.total_value:,.0f}",
              f"${summary.day_change_value:,.0f} today")
    c2.metric("Day return", f"{summary.day_change_pct:+.2f}%",
              f"vs benchmark {bench:+.2f}%" if bench is not None else None)
    c3.metric("Total return", f"{summary.total_return_pct:+.1f}%",
              f"${summary.total_return_value:,.0f} all time")
    best = summary.best()
    c4.metric("Best today", best.ticker, f"{best.day_change_pct:+.2f}%")

    st.subheader("Holdings")
    rows = []
    weights = summary.weights()
    for p in sorted(summary.positions, key=lambda x: x.value, reverse=True):
        rows.append(
            {
                "Ticker": p.ticker,
                "Price": f"${p.price:,.2f}",
                "Day": f"{p.day_change_pct:+.2f}%",
                "Value": f"${p.value:,.0f}",
                "Return": f"{p.total_return_pct:+.1f}%",
                "Weight": f"{weights[p.ticker]:.1f}%",
            }
        )
    st.dataframe(rows, use_container_width=True, hide_index=True)

    col_perf, col_alloc = st.columns([2, 1])

    with col_perf:
        st.subheader("Portfolio vs benchmark · 3M")
        # Build a normalized performance line: portfolio value over time vs SPY.
        bench_candles = get_candles(config.BENCHMARK, 90)
        port_series = None
        for h in config.HOLDINGS:
            c = get_candles(h.ticker, 90)["close"] * h.shares
            port_series = c if port_series is None else port_series.add(c, fill_value=0)
        port_norm = port_series / port_series.iloc[0] * 100
        bench_norm = bench_candles["close"] / bench_candles["close"].iloc[0] * 100

        fig = go.Figure()
        fig.add_trace(go.Scatter(x=list(port_norm.index), y=port_norm.values,
                                 name="Portfolio", line=dict(color=GREEN, width=2)))
        fig.add_trace(go.Scatter(x=list(bench_norm.index), y=bench_norm.values,
                                 name="Benchmark", line=dict(color=GRAY, width=1, dash="dash")))
        fig.update_layout(height=300, margin=dict(l=0, r=0, t=10, b=0),
                          legend=dict(orientation="h", y=1.1),
                          yaxis_title="Indexed to 100")
        st.plotly_chart(fig, use_container_width=True)

    with col_alloc:
        st.subheader("Allocation")
        labels = list(weights.keys())
        values = list(weights.values())
        pie = go.Figure(go.Pie(labels=labels, values=values, hole=0.55,
                               textinfo="label+percent", sort=True))
        pie.update_layout(height=300, margin=dict(l=0, r=0, t=10, b=0),
                          showlegend=False)
        st.plotly_chart(pie, use_container_width=True)

    st.caption(
        "For informational purposes only — not investment advice. "
        + ("Live quotes via Finnhub." if config.is_live()
           else "Running on demo data; set FINNHUB_API_KEY for live quotes.")
    )

# --------------------------------------------------------------------------- #
# Charts tab
# --------------------------------------------------------------------------- #

with tab_charts:
    tickers = [h.ticker for h in config.HOLDINGS]
    sel = st.selectbox("Ticker", tickers)
    days = st.select_slider("History", options=[30, 90, 180, 365], value=90)

    candles = get_candles(sel, days)
    close = candles["close"]

    fig = go.Figure()
    fig.add_trace(go.Candlestick(
        x=list(candles.index),
        open=candles["open"], high=candles["high"],
        low=candles["low"], close=candles["close"],
        name=sel, increasing_line_color=GREEN, decreasing_line_color=RED,
    ))
    fig.add_trace(go.Scatter(x=list(candles.index), y=sma(close, 20),
                             name="SMA 20", line=dict(color="#185FA5", width=1)))
    fig.add_trace(go.Scatter(x=list(candles.index), y=ema(close, 50),
                             name="EMA 50", line=dict(color="#BA7517", width=1)))
    fig.update_layout(height=420, margin=dict(l=0, r=0, t=10, b=0),
                      xaxis_rangeslider_visible=False,
                      legend=dict(orientation="h", y=1.1))
    st.plotly_chart(fig, use_container_width=True)

    rsi_val = latest_rsi(close)
    zone = ("Overbought" if rsi_val > 70 else
            "Oversold" if rsi_val < 30 else "Neutral")
    m1, m2, m3 = st.columns(3)
    m1.metric("Last price", f"${close.iloc[-1]:,.2f}")
    m2.metric("RSI (14)", f"{rsi_val}", zone)
    m3.metric("Range (period)", f"${close.min():,.0f} – ${close.max():,.0f}")

# --------------------------------------------------------------------------- #
# Pipeline & runs tab — the automation story, made visible
# --------------------------------------------------------------------------- #

with tab_pipeline:
    st.subheader("Automated data pipeline")
    st.markdown(
        "A scheduled GitHub Actions job runs every weekday before the US market "
        "open. It fetches quotes, computes indicators, writes the digest, and "
        "commits a fresh `data/snapshot.json` back to the repo. The UI just "
        "renders that snapshot — fetching is decoupled from display."
    )

    steps = ["Cron trigger", "Fetch quotes", "Compute indicators",
             "Write digest", "Commit snapshot"]
    cols = st.columns(len(steps))
    for col, step in zip(cols, steps):
        col.success(step, icon="✅")

    st.divider()
    st.subheader("Last run")
    if snapshot:
        meta = snapshot.get("metrics", {})
        r1, r2, r3, r4 = st.columns(4)
        r1.metric("Generated at", snapshot.get("generated_at", "—"))
        r2.metric("Tickers", meta.get("tickers", len(config.HOLDINGS)))
        r3.metric("API calls", meta.get("api_calls", "—"))
        r4.metric("Duration", f"{meta.get('duration_s', '—')}s")
    else:
        st.info(
            "No snapshot found yet. Run `python pipeline.py` locally, or let the "
            "scheduled GitHub Action produce one. The app falls back to computing "
            "everything on load in the meantime."
        )
